name: "Publish to Krzyśtałki"
on: 
  push:
    paths:
      - "content/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@v2

      - name: setup-pelican
        run: test -f requirements.txt && pip install -r requirements.txt

      - name: build-page
        run: make clean && make html        
      
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: krzystalki-gh-pages
          path: output

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: write
    steps:

      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages
        
      - name: download-artifacts
        uses: actions/download-artifact@v2
        with:
          name: krzystalki-gh-pages

      - name: push-to-gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update GH-Pages"
          git push

